when:
  - event: push
    branch: main

steps:
  deploy-alpha:
    image: docker:27
    commands:
      - export $(cat version.txt)
      - echo $DOCKER_PASSWORD | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker build -f ./resource/docker/Dockerfile -t bc-msh-${CI_REPO_NAME}-deploy .
      - docker run --rm -e CI -e NPM_TOKEN -e GH_USER -e GH_TOKEN bc-msh-${CI_REPO_NAME}-deploy sh -c "npm config set '//registry.npmjs.org/:_authToken' $NPM_TOKEN && npm run npm-bump-version $VERSION-alpha && npm publish --access public --tag alpha && git tag v$VERSION-alpha && git push origin --tags"
    secrets: [ docker_username, docker_password, gh_token, gh_user, npm_token ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
