when:
  - event: push
    branch: main

steps:
  bump-version:
    image: docker:27
    commands:
      - echo $DOCKER_PASSWORD | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker build -f ./resource/docker/Dockerfile -t bc-msh-${CI_REPO_NAME} .
      - touch version.txt
      - docker run --rm -v ./version.txt:/usr/app/version.txt -e GH_TOKEN -e NPM_TOKEN -e GH_USER -e CI bc-msh-${CI_REPO_NAME} npm run npm-semantic-release
      - cat version.txt
    secrets: [ docker_username, docker_password, gh_token, gh_user, npm_token ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
