when:
  - event: push
    branch: main

steps:
  build:
    image: docker:27
    commands:
      - echo $DOCKER_PASSWORD | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker build -f ./resource/docker/Dockerfile -t bc-msh-${CI_REPO_NAME} .
    secrets: [ docker_username, docker_password ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  test:
    image: docker:27
    commands:
      - docker run --rm -e CODECOV_TOKEN bc-msh-${CI_REPO_NAME} sh -c 'npm run test-coverage-unit && npm run test-coverage-unit-publish'
    secrets: [ codecov_token ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: [build]
